#!/usr/bin/env python3
import json
import sys
import os
import logging
import logging.handlers
import requests

ZABBIX_API_URL = "http://127.0.0.1/api_jsonrpc.php"
UNAME = "print_login_here1111"
PWORD = "print_password_here"

r = requests.post(ZABBIX_API_URL,
                  json={
                        "jsonrpc": "2.0",
                        "method": "user.login",
                        "params": {
                        "user": UNAME,
                        "password": PWORD},
                        "id": 1
                  })

#print(json.dumps(r.json(), indent=4, sort_keys=True))


AUTHTOKEN = r.json()["result"]

def get_hostname(hostid):
    j = requests.post(ZABBIX_API_URL,

                json={
                    "jsonrpc": "2.0",
                    "method": "host.get",
                    "params": {
                        "output": ["host"],
                        "filter": {
                            "hostid" : hostid
                        }
                    },
                    "id": 2,
                    "auth": AUTHTOKEN
                })
    data_j = json.dumps(j.json(), indent=4, sort_keys=True)
    data_j_1 = json.loads(data_j)
    dat = (data_j_1['result'])
    if dat == []:
        data_j_j_1 = "Это шаблон, либо хост в статусе Disabled"
    else:
        data_j_j_1 = (data_j_1['result'][0]['host'])
    #data_j_1_1 = (data_j_1)['result']['name']
    #(data_j_1['result'][0]['hostid'])
    return data_j_j_1


def get_history(qwerty):
    q = requests.post(ZABBIX_API_URL,

                json={
                    "jsonrpc": "2.0",
                    "method": "history.get",
                    "params": {
                        "output":"extend",
                        "history": 1,
                        "itemids": qwerty,
                        "sortfield": "clock",
                        "sortorder": "DESC",
                        "limit":1
                    },
                    "id": 2,
                    "auth": AUTHTOKEN
                })
    data_q = json.dumps(q.json(), indent=4, sort_keys=True)
    data_q_1 = json.loads(data_q)
    return data_q_1

items_spisok = []
hosts_spisok = []
items_spisok_1 = []
hosts_spisok_1 = []

def get_items():

    r = requests.post(ZABBIX_API_URL,
                                    json={
                                        "jsonrpc": "2.0",
                                        "method": "item.get",
                                        "params": {
                                            "output": ["hostid",
                                            "key_",
                                            ],
                                            #"hostids": 11232,
                                            "search": {
                                                "key_": "system.hostname"
                                            },
                                            "sortfield": "name",
                                            "limit":1000
                                        },
                                        "id": 2,
                                        "auth": AUTHTOKEN
                                    })

    data = json.dumps(r.json(), indent=4, sort_keys=True)
    data_1 = json.loads(data)

    for items_ids in (data_1)['result']:
        items_spisok.append(int(items_ids['itemid']))
#    print(items_spisok)
#    print(data_1 )
    return(items_spisok)



def get_hosts():

    h = requests.post(ZABBIX_API_URL,
                                    json={
                                        "jsonrpc": "2.0",
                                        "method": "item.get",
                                        "params": {
                                            "output": ["hostid",
                                            "key_",
                                            ],
                                            #"hostids": 11232,
                                            "search": {
                                                "key_": "system.hostname"
                                            },
                                            "sortfield": "name",
                                            "limit":1000
                                        },
                                        "id": 2,
                                        "auth": AUTHTOKEN
                                    })

    data_b = json.dumps(h.json(), indent=4, sort_keys=True)
    data_b_1 = json.loads(data_b)

    for hosts_ids_1 in (data_b_1)['result']:
        hosts_spisok_1.append(int(hosts_ids_1['hostid']))
#    print(items_spisok)
#    print(data_1 )
#    print(hosts_spisok_1)
    return(hosts_spisok_1)



def main():

    ab = get_items()
    cd = get_hosts()

    for items,hostid in zip(ab,cd):
        print("Хост id: ",hostid)
        print("Имя хоста: ",get_hostname(hostid))
        print("Данные по метрике: ",get_history(items))
        print(" ")


main()

